---
title: "Bienvenida"
description: "Primera nota: por qué he creado esta web."
date: 2026-09-24
categories: [personal]
---

Hola. Esta es mi primera nota de la web, así que, quería saludarte antes de todo :)

No me gustan demasiado las redes sociales, por ello no tengo ni Instagram, TikTok o incluso Linkedin. 
Aunque sí es cierto que tengo X/Twitter, pero el algoritmo entrenado por mí mismo de tal manera que es solo 
meterte en la aplicación y te empiece a aburrir XD. 

No obstante, Linkedin me gustaba bastante, pero desde mi punto de vista, se ha convertido en algo que no me gusta (me reservo la opinión :P). 
Por tanto, durante mucho tiempo pensé de crear mi página web personal que sirviera para poder reemplazar este tipo de redes sociales, con la diferencia de que no existen algoritmos adictivos que te hacen scrollear mucho tiempo, y bueno, la restricción de tener que ajustarme a la manera de que cada red social te obliga a publicar contenido.

Así, nace este proyecto con mucha ilusión y, además, con un diseño que evoca al lugar donde nací. Así como, algunos easter eggs :)

En él, además de servir como portfolio, le daré las siguientes utilidades:

- Publicación de notas tanto profesionales como personales.
- Mantendré actualizada mi biblioteca digital que no es más que un enlace simbólico a mi biblioteca física. No obstante, está sin acabar y la iré construyendo poco a poco con el paso del tiempo.
- Sección de aventuras. Como una alacena donde iré guardando recuerdos y experiencias para que perduren en el tiempo.

Y bueno, hasta aquí la nota. 
Si habeís llegado hasta aquí leyendo, me apiado de vosotros, ya que aguantarme seguro que no ha tenido que ser muy fácil jeje.


Post data (Detrás de los datos ?): esta sección es un poco más informal y personal, así que, el estilo de escritura, palabras usadas, entre otras cosas, se adaptarán a ello. Ademaś de que en esta sección ESTÁ PROHIBIDO EL USO DE IA.

